# Generated by Django 4.1.5 on 2023-06-04 20:41

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_email', models.CharField(max_length=80)),
                ('doctor_email', models.CharField(max_length=80)),
                ('doctor_name', models.CharField(max_length=64)),
                ('doctor_last_name', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=64)),
                ('patient_last_name', models.CharField(max_length=100)),
                ('patient_birth_date', models.CharField(max_length=20)),
                ('medical_information', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=64)),
                ('patient_name', models.CharField(max_length=64)),
                ('doctor_last_name', models.CharField(max_length=100)),
                ('patient_last_name', models.CharField(max_length=100)),
                ('doctor_email', models.CharField(max_length=100)),
                ('patient_email', models.CharField(max_length=100)),
                ('doctor_id', models.CharField(max_length=50)),
                ('week_day', models.CharField(max_length=30)),
                ('working_day', models.BooleanField(default=True)),
                ('date', models.CharField(max_length=20)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('speciality', models.CharField(blank=True, max_length=40)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
